### ISSUE TITLE
投稿日時、発言者などふくめ、プロパティを通信する

### ISSUE THREAD

**Issue by otiai10** [otiai10/ojisan.py#2]
json_encodeてきな

**Comment by otiai10** [comment]
プロパティの通信はできるようになった

**Comment by cassy1003** [comment]
:clap:

**Comment by otiai10** [comment]
お名前どっとこむいじってたらNS狂ってやばい otiai10.com 死んだ

**Comment by otiai10** [comment]
http://www15224uf.sakura.ne.jp:9090/

@cassy1003

**Comment by cassy1003** [comment]
:crying_cat_face:

**Comment by otiai10** [comment]
@cassy1003 ちゅーかコレかなり抜本的に作り直すので、今止めてる
