### ISSUE TITLE
顔文字ふやす

### ISSUE THREAD

**Issue by otiai10** [otiai10/ojisan.py#6]

**Comment by kamatari** [comment]
(´∀｀)・(；´Д｀)・(=ﾟωﾟ)ﾉ・(・∀・)ｲｲ!!・('A`)・щ(ﾟдﾟщ)ｶﾓｰﾝ・＼(^o^)／・(´-ω-｀)…zZ乙・(*ﾟдﾟ)ﾑﾎﾑﾎ
