### ISSUE TITLE
クロスサイトスクリプティング

### ISSUE THREAD

**Issue by otiai10** [otiai10/ojisan.py#7]

**Comment by kazz187** [comment]
簡単な攻撃例

<pre>
$('body').css('background-image', 'url("http://asa.oti10.com:9090/img/goodmorning.jpg")');
</pre>

もどすスクリプト

<pre>
$('body').css('background-image', '');
</pre>

**Comment by kazz187** [comment]
プロモーションスクリプト

<pre>
location.href="http://anitick.net"
</pre>

**Comment by otiai10** [comment]
https://github.com/otiai10/ojisan/commit/e7c670804aecf28ba7f034df04848f92429e0a00
